// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2gLFeN-uAtM-kn8ka3g8r0DyUC2Rd7pc',
    appId: '1:322015480465:web:0fd8c9542548d8dd95cd30',
    messagingSenderId: '322015480465',
    projectId: 'chatsocketpractice',
    authDomain: 'chatsocketpractice.firebaseapp.com',
    storageBucket: 'chatsocketpractice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAs-o9e42wjQpuTUKoYLuz0pgAMwilW1I',
    appId: '1:322015480465:android:b13b161483b460a395cd30',
    messagingSenderId: '322015480465',
    projectId: 'chatsocketpractice',
    storageBucket: 'chatsocketpractice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXB_7n6neuT8_LuHJ-8LHPwAjloMpA4OE',
    appId: '1:322015480465:ios:3d9d1ec0f81d25f195cd30',
    messagingSenderId: '322015480465',
    projectId: 'chatsocketpractice',
    storageBucket: 'chatsocketpractice.firebasestorage.app',
    iosBundleId: 'com.example.chatSocketPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXB_7n6neuT8_LuHJ-8LHPwAjloMpA4OE',
    appId: '1:322015480465:ios:3d9d1ec0f81d25f195cd30',
    messagingSenderId: '322015480465',
    projectId: 'chatsocketpractice',
    storageBucket: 'chatsocketpractice.firebasestorage.app',
    iosBundleId: 'com.example.chatSocketPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2gLFeN-uAtM-kn8ka3g8r0DyUC2Rd7pc',
    appId: '1:322015480465:web:8db2b7710b30d38b95cd30',
    messagingSenderId: '322015480465',
    projectId: 'chatsocketpractice',
    authDomain: 'chatsocketpractice.firebaseapp.com',
    storageBucket: 'chatsocketpractice.firebasestorage.app',
  );
}
